name: Test

on:
  pull_request:
jobs:
  ios-sdk-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test
        run:  xcodebuild clean test -project Hackle.xcodeproj -scheme Hackle-Package -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest'
