name: update sdk version

on:
  create:

jobs:
  create-dev-branch:
    if: github.ref_type == 'branch' && startsWith(github.ref, 'refs/heads/dev-')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get branch name
        id: get_branch
        run: echo "branch=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}

      - name: Extract version from branch name
        id: extract_version
        run: |
          BRANCH_NAME="${{ steps.get_branch.outputs.branch }}"
          # dev-*.*.*에서 버전 추출
          if [[ "$BRANCH_NAME" =~ ^dev-([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            VERSION="${BASH_REMATCH[1]}"
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "Extracted version: $VERSION"
          else
            echo "Not a dev-x.x.x branch"
            exit 1
          fi

      - name: Update iOS SDK
        run: |
          # pod 버전 업데이트
          sed -i -E 's/(spec\.version *=[[:space:]]*")[0-9]+\.[0-9]+\.[0-9]+(")/\1${{ steps.extract_version.outputs.version }}\2/' Hackle.podspec
          # package 버전업데이트
          sed -i -E 's/(static let CURRENT = ")[0-9]+\.[0-9]+\.[0-9]+(")/\1${{ steps.extract_version.outputs.version }}\2/' Sources/Hackle/Core/Utilities/SdkVersion.swift

      - name: Push New Version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: update sdk version"
          git push origin
